#!/usr/bin/env node
/**
 * Build the combined public Matrix homeserver list served at
 * https://prinny.app/api/servers.json
 *
 * Three upstream lists are merged and deduplicated:
 *
 *   asra       https://wiki.asra.gr/en:public_servers
 *              ~1100 rows. Autogenerated crawl of every federating server with
 *              open registration, as seen by asra.gr. Broad but shallow:
 *              name, delegated server, software, version, last check.
 *
 *   joinmatrix https://servers.joinmatrix.org/servers.json
 *              ~25 public + ~22 private. Small but curated and by far the
 *              richest: ISP, jurisdiction, rules/privacy links, registration
 *              method, languages, features, ipv6, sliding sync.
 *
 *   privacydev https://www.privacydev.net/matrix_instances.csv
 *              ~35 rows of privacy posture: Tor friendliness, Cloudflare,
 *              whether email is required, reCAPTCHA/hCaptcha, similarweb rank.
 *
 * WHY THIS RUNS IN CI AND NOT IN THE CLIENT
 * -----------------------------------------
 * None of the three upstreams send an Access-Control-Allow-Origin header, so a
 * browser cannot fetch any of them directly — verified, not assumed:
 *
 *     curl -sD- -o/dev/null -H 'Origin: https://example.com' <url> | grep -i access-control
 *
 * returns nothing for all three, while the api.matrixrooms.info endpoint this
 * replaces returns `access-control-allow-origin: *` (that is the control that
 * makes the negative result meaningful). GitHub Pages *does* send `*`, so the
 * merge happens here, daily, and every client — web, desktop, Android — reads
 * one same-origin-friendly JSON file.
 *
 * WHY THERE IS A PROXY ROUTE
 * --------------------------
 * privacydev.net drops TCP from GitHub Actions' egress addresses. Measured,
 * not assumed:
 *
 *   · every attempt of every scheduled run failed after 10.5s, to the
 *     half-second, across 21 consecutive days (2026-08-11 onwards). 10s is
 *     undici's default connect timeout — a SYN with no SYN-ACK, not a slow
 *     server, not TLS, not DNS, and not an HTTP status.
 *   · the identical request (same URL, same user-agent, same accept header)
 *     from a non-cloud address returns 200 with the full CSV in 0.7s. That is
 *     the control that makes the negative result mean something.
 *   · asra.gr and joinmatrix.org were fetched live in those same runs, so it
 *     is that host, not the runner's network.
 *
 * The run stayed green throughout: the cache fallback did its job and the
 * source silently aged to 21 days. Hence both halves of the fix — a second
 * egress to actually get the file, and an alarm so a source that stops
 * refreshing cannot age quietly again.
 *
 * A NOTE ON THE asra.gr POSTGRES DSN
 * ----------------------------------
 * The wiki page embeds a `<sql db="pgsql://...">` tag whose credentials are
 * visible in the page source. We deliberately do NOT use it. The host is
 * 172.23.216.251 — RFC1918, i.e. asra.gr's internal network and unreachable
 * from here anyway — and connecting to a third party's database with
 * credentials leaked by their own template would be unauthorised access, not
 * an integration. The rendered HTML table carries the same data and is the
 * published, intended-for-consumption surface. Parse that.
 */

import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { execFile } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

const execFileAsync = promisify(execFile);

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const API_DIR = path.join(ROOT, 'api');
// Deliberately outside api/ so it is never published by Pages. This directory
// IS committed: it is what keeps a temporarily unreachable upstream (see the
// privacydev note above) from emptying that source out of the API.
const CACHE_DIR = path.join(ROOT, '.server-cache');
const OUT_FILE = path.join(API_DIR, 'servers.json');

const SCHEMA_VERSION = 1;

const SOURCES = {
  asra: 'https://wiki.asra.gr/en:public_servers',
  joinmatrix: 'https://servers.joinmatrix.org/servers.json',
  privacydev: 'https://www.privacydev.net/matrix_instances.csv',
};

const USER_AGENT =
  'prinny.app-server-list/1.0 (+https://github.com/coffeegrind123/prinny.app; daily merge of public Matrix server lists)';

// Bounds a slow *body*, not a dead connection. Worth being explicit about,
// because it was raised to 120s on the theory that privacydev.net was merely
// slow and that turned out to bound nothing at all: undici applies its own
// 10s connect timeout, and an AbortController deadline can only fire after a
// socket exists. Every privacydev failure measured to 10.5s — the connect
// timeout, not this one. Keep it generous for genuinely slow bodies; do not
// expect it to influence a connect that never completes.
const FETCH_TIMEOUT_MS = 120_000;
const WELLKNOWN_TIMEOUT_MS = 8_000;
const WELLKNOWN_CONCURRENCY = 8;

// A direct connect failure is worth retrying — an upstream can drop a
// connection for a minute and come back. It is NOT worth retrying five times
// when a working proxy is configured, because the failure we actually see is
// an egress block, and no amount of backoff moves an egress block. Burn two
// attempts to catch the transient case, then change route.
const FETCH_RETRIES = 5;
const FETCH_RETRIES_WITH_PROXY = 2;
const FETCH_BACKOFF_MS = 15_000;

// Egress of last resort. Same residential proxy the tennisnews scraper uses
// (its UPSTREAM_PROXY secret); the workflow passes it in as PRINNY_HTTP_PROXY.
// Unset locally and in any fork without the secret, in which case every fetch
// is direct and behaviour is exactly as it was before.
const HTTP_PROXY =
  process.env.PRINNY_HTTP_PROXY ||
  process.env.HTTPS_PROXY ||
  process.env.https_proxy ||
  '';
// Skip the direct attempt entirely. For testing the proxy path, and usable as
// an ops switch if an upstream ever blocks us permanently enough to be worth
// not waiting on.
const PROXY_ONLY = process.env.PRINNY_PROXY_ONLY === '1';
const PROXY_RETRIES = 3;
// A residential exit is a shared address and gets a fair share of one-off
// resets; retry quickly rather than with the direct route's long backoff.
const PROXY_BACKOFF_MS = 5_000;
// Proxy connect budget. Residential exits are slow to establish; the direct
// route's implicit 10s is too tight for one.
const PROXY_CONNECT_TIMEOUT_S = 30;

// How long a cached source may go without a live refresh before the run is
// worth a red tick rather than a line in a log nobody reads. Three days is
// two missed crons plus slack — well short of the 21 days privacydev spent
// silently stale before anyone noticed.
const STALE_ALARM_DAYS = 3;

// ---------------------------------------------------------------------------
// small helpers
// ---------------------------------------------------------------------------

const log = (...args) => console.log('[servers]', ...args);
const warn = (...args) => console.warn('[servers] WARN', ...args);

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// GitHub Actions annotations. Outside CI these are just prefixed lines.
const annotate = (level, msg) => console.log(`::${level}::${msg}`);

/**
 * undici reports every transport failure as the same three characters —
 * `fetch failed` — and hides what actually happened in `err.cause`. Logging
 * only `err.message` is what let a hard egress block read as "the site is
 * down" for three weeks. Unwrap the chain.
 */
function describeError(err) {
  if (!err) return 'unknown error';
  const parts = [];
  for (let e = err, depth = 0; e && depth < 4; e = e.cause, depth += 1) {
    const code = e.code ? ` ${e.code}` : '';
    const msg = e.message || String(e);
    const text = `${e.name || 'Error'}${code}: ${msg}`;
    if (!parts.includes(text)) parts.push(text);
  }
  return redactProxy(parts.join(' <- '));
}

/** Never let proxy credentials reach a log line, an error or api/servers.json. */
function redactProxy(text) {
  return String(text).replace(/\/\/[^/@\s]+@/g, '//***@');
}

async function fetchOnce(url, { timeout = FETCH_TIMEOUT_MS, accept } = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeout);
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      redirect: 'follow',
      headers: {
        'user-agent': USER_AGENT,
        ...(accept ? { accept } : {}),
      },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.text();
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Same request, different egress, via curl's HTTP proxy support.
 *
 * Node 22 has no supported way to point `fetch` at a proxy: `ProxyAgent` lives
 * in undici, which ships *inside* Node but is not exported from any `node:`
 * module, and Node's own `NODE_USE_ENV_PROXY` landed after 22. Shelling out to
 * curl keeps this script free of npm dependencies (the property the workflow
 * relies on to run with no install step) and buys far better diagnostics
 * besides: curl distinguishes "cannot reach proxy" from "proxy refused auth"
 * from "origin timed out", where `fetch` says only `fetch failed`.
 */
async function fetchViaProxy(url, { timeout = FETCH_TIMEOUT_MS, accept } = {}) {
  const bodyFile = path.join(tmpdir(), `prinny-fetch-${randomUUID()}`);
  const args = [
    '--silent',
    '--show-error',
    '--location',
    '--max-redirs',
    '5',
    '--proxy',
    HTTP_PROXY,
    '--connect-timeout',
    String(PROXY_CONNECT_TIMEOUT_S),
    '--max-time',
    String(Math.ceil(timeout / 1000)),
    '--user-agent',
    USER_AGENT,
    ...(accept ? ['--header', `accept: ${accept}`] : []),
    '--output',
    bodyFile,
    '--write-out',
    '%{http_code}',
    url,
  ];
  try {
    let stdout;
    try {
      ({ stdout } = await execFileAsync('curl', args, { maxBuffer: 64 * 1024 * 1024 }));
    } catch (err) {
      // curl's own failure (exit code + stderr), which may quote the proxy URL.
      const detail = redactProxy((err.stderr || err.message || '').trim().split('\n')[0]);
      throw new Error(`curl exit ${err.code ?? '?'}${detail ? `: ${detail}` : ''}`);
    }
    const status = Number.parseInt(stdout.trim(), 10);
    if (!Number.isFinite(status)) throw new Error('proxy: no status from curl');
    if (status < 200 || status >= 300) throw new Error(`HTTP ${status}`);
    return await readFile(bodyFile, 'utf8');
  } finally {
    await rm(bodyFile, { force: true });
  }
}

/**
 * Fetch with retries, falling back to the proxy route when the direct one
 * cannot get an answer at all.
 *
 * Returns { text, via } so the caller can record which egress actually worked
 * — the thing that would have made the privacydev outage obvious on day one.
 */
async function fetchTextVia(url, { retries, proxyFallback = true, ...opts } = {}) {
  const useProxy = proxyFallback && Boolean(HTTP_PROXY);
  const directRetries = retries ?? (useProxy ? FETCH_RETRIES_WITH_PROXY : FETCH_RETRIES);
  const skipDirect = useProxy && PROXY_ONLY;
  let lastErr = new Error('PRINNY_PROXY_ONLY=1 — direct route not attempted');

  if (!skipDirect) {
    for (let attempt = 1; attempt <= directRetries; attempt += 1) {
      try {
        return { text: await fetchOnce(url, opts), via: 'direct' };
      } catch (err) {
        lastErr = err;
        // A 4xx is a real answer — retrying will not change it, and neither
        // will another exit IP.
        if (/^HTTP 4\d\d$/.test(err.message)) throw err;
        if (attempt < directRetries) {
          const wait = FETCH_BACKOFF_MS * attempt;
          warn(
            `${url} attempt ${attempt}/${directRetries} failed ` +
              `(${describeError(err)}); retrying in ${wait}ms`,
          );
          await sleep(wait);
        }
      }
    }
  }

  if (!useProxy) throw lastErr;

  if (skipDirect) log(`${url}: PRINNY_PROXY_ONLY=1 — going straight to the proxy`);
  else warn(`${url}: direct route failed (${describeError(lastErr)}) — trying proxy`);
  let proxyErr;
  for (let attempt = 1; attempt <= PROXY_RETRIES; attempt += 1) {
    try {
      const text = await fetchViaProxy(url, opts);
      log(`${url}: proxy route succeeded on attempt ${attempt}`);
      return { text, via: 'proxy' };
    } catch (err) {
      proxyErr = err;
      if (/^HTTP 4\d\d$/.test(err.message)) break;
      if (attempt < PROXY_RETRIES) {
        const wait = PROXY_BACKOFF_MS * attempt;
        warn(
          `${url} proxy attempt ${attempt}/${PROXY_RETRIES} failed ` +
            `(${describeError(err)}); retrying in ${wait}ms`,
        );
        await sleep(wait);
      }
    }
  }
  throw new Error(
    `both routes failed — direct: ${describeError(lastErr)}; ` +
      `proxy: ${describeError(proxyErr)}`,
  );
}

async function fetchText(url, opts = {}) {
  return (await fetchTextVia(url, opts)).text;
}

/**
 * Domain → comparable key. Lowercased, port stripped, trailing dot stripped.
 * A value that is not a plausible hostname returns '' so it can never become a
 * merge key (merging on '' would collapse unrelated servers into one).
 */
const HOSTNAME_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;

function normDomain(value) {
  if (typeof value !== 'string') return '';
  let d = value.trim().toLowerCase();
  if (!d) return '';
  // Accept a full URL and take its host.
  if (d.includes('://')) {
    try {
      d = new URL(d).hostname;
    } catch {
      return '';
    }
  }
  d = d.split('/')[0];
  // Strip a :port, but leave IPv6 literals alone (we reject them below anyway).
  const colon = d.lastIndexOf(':');
  if (colon > -1 && !d.includes('[')) d = d.slice(0, colon);
  d = d.replace(/\.+$/, '');
  if (!HOSTNAME_RE.test(d)) return '';
  if (d.length > 253) return '';
  return d;
}

function cleanText(value, maxLen = 500) {
  if (typeof value !== 'string') return '';
  const t = value.replace(/\s+/g, ' ').trim();
  return t.length > maxLen ? t.slice(0, maxLen) : t;
}

/** Only http(s) URLs survive — these end up as hrefs in the client. */
function cleanUrl(value) {
  if (typeof value !== 'string') return '';
  const t = value.trim();
  if (!t) return '';
  try {
    const u = new URL(t);
    if (u.protocol !== 'https:' && u.protocol !== 'http:') return '';
    return u.toString();
  } catch {
    return '';
  }
}

const yesNo = (value) => {
  const t = String(value ?? '').trim().toLowerCase();
  if (t === 'yes' || t === 'true' || t === '1') return true;
  if (t === 'no' || t === 'false' || t === '0') return false;
  return null; // '?' and '' both mean "unknown", which is not the same as false
};

async function mapLimit(items, limit, fn) {
  const results = new Array(items.length);
  let cursor = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (;;) {
      const i = cursor;
      cursor += 1;
      if (i >= items.length) return;
      results[i] = await fn(items[i], i);
    }
  });
  await Promise.all(workers);
  return results;
}

// ---------------------------------------------------------------------------
// source parsers
// ---------------------------------------------------------------------------

const HTML_ENTITIES = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  '#039': "'",
  apos: "'",
  nbsp: ' ',
  hellip: '…',
};

function decodeEntities(s) {
  return s.replace(/&(#x?[0-9a-f]+|[a-z0-9#]+);/gi, (m, ent) => {
    const key = ent.toLowerCase();
    if (HTML_ENTITIES[key]) return HTML_ENTITIES[key];
    if (key.startsWith('#x')) {
      const code = parseInt(key.slice(2), 16);
      return Number.isFinite(code) ? String.fromCodePoint(code) : m;
    }
    if (key.startsWith('#')) {
      const code = parseInt(key.slice(1), 10);
      return Number.isFinite(code) ? String.fromCodePoint(code) : m;
    }
    return m;
  });
}

const stripTags = (s) => decodeEntities(s.replace(/<[^>]*>/g, ' ')).replace(/\s+/g, ' ').trim();

/**
 * asra.gr renders a DokuWiki table with the columns
 *   Name | Server | Software | Version | Last Check
 * The same page also renders a two-column FAQ table, so rows are accepted only
 * when they have exactly five cells and the first one looks like a domain.
 */
function parseAsra(html) {
  const out = [];
  const rows = html.match(/<tr[^>]*>[\s\S]*?<\/tr>/gi) ?? [];
  for (const row of rows) {
    const cells = (row.match(/<t[dh][^>]*>[\s\S]*?<\/t[dh]>/gi) ?? []).map(stripTags);
    if (cells.length !== 5) continue;
    const name = normDomain(cells[0]);
    if (!name) continue;

    // The crawler writes the literal string 'null' when it could not identify
    // the daemon. Treat that and '' identically: unknown.
    const softwareRaw = cleanText(cells[2], 60);
    const software = softwareRaw && softwareRaw.toLowerCase() !== 'null' ? softwareRaw : '';
    const versionRaw = cleanText(cells[3], 60);
    const version = versionRaw && versionRaw.toLowerCase() !== 'null' ? versionRaw : '';

    out.push({
      name,
      // The delegated client server. Frequently equal to name.
      client_domain: normDomain(cells[1]),
      software,
      version,
      last_check: parseAsraTimestamp(cells[4]),
    });
  }
  if (out.length === 0) throw new Error('asra: parsed zero server rows (page layout changed?)');
  return out;
}

/** '2026-08-10 20:46:42+00' → ISO 8601, or '' when unparseable. */
function parseAsraTimestamp(value) {
  const t = cleanText(value, 40);
  if (!t) return '';
  const iso = t.replace(' ', 'T').replace(/\+00$/, 'Z').replace(/([+-]\d{2})$/, '$1:00');
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? '' : d.toISOString();
}

function parseJoinMatrix(text) {
  const data = JSON.parse(text);
  const out = [];
  const take = (list, registrationOpen) => {
    if (!Array.isArray(list)) return;
    for (const e of list) {
      if (!e || typeof e !== 'object') continue;
      const name = normDomain(e.name);
      if (!name) continue;
      out.push({
        name,
        client_domain: normDomain(e.client_domain),
        server_domain: normDomain(e.server_domain),
        software: cleanText(e.software, 60),
        version: cleanText(e.version, 60),
        registration_open: registrationOpen,
        using_vanilla_reg: e.using_vanilla_reg === true,
        reg_method: cleanText(e.reg_method, 80),
        reg_link: cleanUrl(e.reg_link),
        captcha: typeof e.captcha === 'boolean' ? e.captcha : null,
        captcha_note: cleanText(e.captcha_note, 200),
        email: typeof e.email === 'boolean' ? e.email : null,
        homepage: cleanUrl(e.homepage),
        rules: cleanUrl(e.rules),
        privacy_policy: cleanUrl(e.privacy),
        description: cleanText(e.description, 400),
        isp: cleanText(e.isp, 120),
        jurisdiction: cleanText(e.staff_jur, 120),
        languages: Array.isArray(e.languages)
          ? e.languages.map((l) => cleanText(l, 40)).filter(Boolean).slice(0, 12)
          : [],
        features: Array.isArray(e.features)
          ? e.features.map((f) => cleanText(f, 60)).filter(Boolean).slice(0, 12)
          : [],
        longstanding: e.longstanding === true,
        ipv6: typeof e.ipv6 === 'boolean' ? e.ipv6 : null,
        sliding_sync: typeof e.sliding_sync === 'boolean' ? e.sliding_sync : null,
        online_status: Number.isFinite(e.online_status) ? e.online_status : null,
        ver_status: Number.isFinite(e.ver_status) ? e.ver_status : null,
        room_directory: Number.isFinite(e.room_directory) ? e.room_directory : null,
      });
    }
  };
  take(data.public_servers, true);
  take(data.private_servers, false);
  if (out.length === 0) throw new Error('joinmatrix: parsed zero servers');
  return out;
}

/** Semicolon-delimited, with a quoted-field-aware splitter just in case. */
function parseCsvLine(line) {
  const cells = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (quoted) {
      if (ch === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i += 1;
        } else quoted = false;
      } else cur += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ';') {
      cells.push(cur);
      cur = '';
    } else cur += ch;
  }
  cells.push(cur);
  return cells;
}

function parsePrivacyDev(text) {
  const lines = text.split(/\r?\n/).filter((l) => l.trim());
  if (lines.length < 2) throw new Error('privacydev: empty csv');
  const header = parseCsvLine(lines[0]).map((h) => h.trim().toLowerCase());
  const col = (n) => header.indexOf(n);
  const iServer = col('server');
  if (iServer === -1) throw new Error('privacydev: no "server" column');

  const idx = {
    stable: col('stable'),
    tor: col('tor friendly'),
    cloudflare: col('cloudflare'),
    email: col('email required'),
    recaptcha: col('recaptcha'),
    hcaptcha: col('hcaptcha'),
    rank: col('similarweb rank'),
  };
  const cell = (cells, i) => (i >= 0 && i < cells.length ? cells[i].trim() : '');

  const out = [];
  for (const line of lines.slice(1)) {
    const cells = parseCsvLine(line);
    // privacydev lists the CLIENT host (matrix.example.org), not always the
    // mxid domain — reconciling that is what linkAcrossSources() is for.
    const domain = normDomain(cell(cells, iServer));
    if (!domain) continue;
    const rankRaw = cell(cells, idx.rank);
    const rank = /^\d+$/.test(rankRaw) ? Number(rankRaw) : null;
    out.push({
      domain,
      stable: yesNo(cell(cells, idx.stable)),
      tor_friendly: yesNo(cell(cells, idx.tor)),
      cloudflare: yesNo(cell(cells, idx.cloudflare)),
      email_required: yesNo(cell(cells, idx.email)),
      recaptcha: yesNo(cell(cells, idx.recaptcha)),
      hcaptcha: yesNo(cell(cells, idx.hcaptcha)),
      similarweb_rank: rank,
    });
  }
  if (out.length === 0) throw new Error('privacydev: parsed zero rows');
  return out;
}

// ---------------------------------------------------------------------------
// fetch with per-source cache fallback
//
// A single upstream being down must not empty the API. Each source's parsed
// payload is cached; on failure we serve the last good copy and mark the
// source `stale` in the output so consumers can see it.
// ---------------------------------------------------------------------------

/**
 * Read a source from a local file instead of the network when
 * PRINNY_SRC_<ID> is set (e.g. PRINNY_SRC_PRIVACYDEV=/tmp/pd.csv). Used to
 * seed the cache and to test the merge offline while an upstream is
 * rate-limiting us.
 */
function localOverride(id) {
  return process.env[`PRINNY_SRC_${id.toUpperCase()}`] || '';
}

async function loadSource(id, parse, { accept } = {}) {
  const cacheFile = path.join(CACHE_DIR, `${id}.json`);
  try {
    const override = localOverride(id);
    let text;
    let via = 'local';
    if (override) {
      log(`${id}: reading local override ${override}`);
      text = await readFile(override, 'utf8');
    } else {
      ({ text, via } = await fetchTextVia(SOURCES[id], { accept }));
    }
    const data = parse(text);
    await mkdir(CACHE_DIR, { recursive: true });
    await writeFile(
      cacheFile,
      JSON.stringify({ fetched_at: new Date().toISOString(), via, data }, null, 0),
    );
    log(`${id}: ${data.length} entries (live, via ${via})`);
    return { id, url: SOURCES[id], ok: true, stale: false, via, count: data.length, data };
  } catch (err) {
    // describeError, not err.message: undici's `fetch failed` says nothing,
    // and "which layer failed" is the whole diagnosis.
    const detail = describeError(err);
    warn(`${id}: fetch/parse failed — ${detail}`);
    if (existsSync(cacheFile)) {
      try {
        const cached = JSON.parse(await readFile(cacheFile, 'utf8'));
        warn(`${id}: serving cached copy from ${cached.fetched_at}`);
        return {
          id,
          url: SOURCES[id],
          ok: false,
          stale: true,
          error: detail,
          fetched_at: cached.fetched_at,
          count: cached.data.length,
          data: cached.data,
        };
      } catch (cacheErr) {
        warn(`${id}: cache unreadable — ${cacheErr.message}`);
      }
    }
    return { id, url: SOURCES[id], ok: false, stale: true, error: detail, count: 0, data: [] };
  }
}

// ---------------------------------------------------------------------------
// deduplication
//
// The three lists key on different things. asra and joinmatrix use the mxid
// domain (tchncs.de); privacydev uses the client host (matrix.tchncs.de). Of 35
// privacydev rows, exactly 1 matches an asra name directly.
//
// Stage 1 unions records that share ANY known domain (name / client_domain /
// server_domain) — that is evidence already present in the data.
//
// Stage 2 handles the rest with `.well-known/matrix/client`, the authoritative
// answer to "which mxid domain does this host serve?". A bare `matrix.` strip
// would be wrong: tetaneutral.net delegates to tetaneutral.net, NOT to
// matrix.tetaneutral.net, and envs.net serves no delegation at all. Every link
// made here records how it was made, in `link_evidence`.
// ---------------------------------------------------------------------------

class UnionFind {
  constructor() {
    this.parent = new Map();
  }

  add(key) {
    if (!this.parent.has(key)) this.parent.set(key, key);
  }

  find(key) {
    this.add(key);
    let root = key;
    while (this.parent.get(root) !== root) root = this.parent.get(root);
    // path compression
    let cur = key;
    while (this.parent.get(cur) !== root) {
      const next = this.parent.get(cur);
      this.parent.set(cur, root);
      cur = next;
    }
    return root;
  }

  union(a, b) {
    const ra = this.find(a);
    const rb = this.find(b);
    if (ra !== rb) this.parent.set(ra, rb);
  }
}

async function resolveWellKnown(domain) {
  try {
    // No retries: most domains legitimately serve no delegation at all, so a
    // failure here is the expected answer rather than a transient fault.
    // Retrying it four times with backoff would add minutes for no new
    // information.
    const text = await fetchText(`https://${domain}/.well-known/matrix/client`, {
      timeout: WELLKNOWN_TIMEOUT_MS,
      accept: 'application/json',
      retries: 1,
      // Dozens of hosts, most of which legitimately serve nothing. Sending
      // that through a metered residential exit would cost real bandwidth to
      // learn nothing, and these lookups are not the ones being blocked.
      proxyFallback: false,
    });
    const data = JSON.parse(text);
    const base = data?.['m.homeserver']?.base_url;
    return normDomain(base);
  } catch {
    return '';
  }
}

/**
 * Resolve privacydev hosts that stage 1 could not attach to anything.
 *
 * A row such as `matrix.example.org` is a *client host*; the mxid domain is
 * `example.org`. We ask `example.org` what it delegates to and accept the link
 * ONLY when the answer points back at exactly this host. That does two jobs at
 * once: it merges the row with any asra/joinmatrix entry filed under the mxid
 * domain, and — for rows no other list knows about — it recovers the correct
 * mxid domain, which is what a user actually needs (it is the part after the
 * colon in their user ID, and what the login flow should be handed).
 *
 * Deliberately NOT a `matrix.`-strip: tetaneutral.net delegates to
 * tetaneutral.net rather than matrix.tetaneutral.net, and envs.net serves no
 * delegation at all, so stripping would invent two false identities. Anything
 * without positive proof is left exactly as the source stated it.
 *
 * Returns host → { mxid_domain, evidence }.
 */
async function linkAcrossSources(uf, unresolved) {
  if (unresolved.length === 0) return new Map();
  log(`resolving .well-known for ${unresolved.length} unmatched privacydev hosts…`);

  const resolved = new Map();
  let unverified = 0;

  await mapLimit(unresolved, WELLKNOWN_CONCURRENCY, async (host) => {
    const parts = host.split('.');
    // A two-label domain is already the mxid domain; there is no parent to try.
    if (parts.length < 3) return;
    const parent = parts.slice(1).join('.');

    const delegated = await resolveWellKnown(parent);
    if (!delegated) return;
    if (delegated !== host) {
      // The parent is a homeserver, but it does not point here. Could be the
      // same operator, could be unrelated. No proof, so no merge.
      unverified += 1;
      return;
    }

    uf.union(host, parent);
    resolved.set(host, {
      mxid_domain: parent,
      evidence: {
        linked_to: parent,
        method: 'well-known',
        detail: `https://${parent}/.well-known/matrix/client → ${delegated}`,
      },
    });
  });

  log(
    `.well-known confirmed ${resolved.size}/${unresolved.length} hosts` +
      (unverified ? ` (${unverified} parents delegate elsewhere — left unmerged)` : ''),
  );
  return resolved;
}

// ---------------------------------------------------------------------------
// merge
// ---------------------------------------------------------------------------

/**
 * Drop keys carrying no information — null, '', [], and objects left empty
 * after their own pruning. 1075 of the ~1150 servers are known only to asra,
 * which supplies five fields, so the untrimmed record is ~640 bytes of mostly
 * null scaffolding.
 *
 * `false` and `0` are NOT dropped: "registration.open: false" and
 * "ipv6: false" are answers, and conflating them with "unknown" would be a
 * data bug. Consumers must therefore treat an absent key as unknown.
 */
function prune(value) {
  if (Array.isArray(value)) return value.length ? value : undefined;
  if (value && typeof value === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(value)) {
      const pv = prune(v);
      if (pv !== undefined) out[k] = pv;
    }
    return Object.keys(out).length ? out : undefined;
  }
  if (value === null || value === '') return undefined;
  return value;
}

function pickFirst(...values) {
  for (const v of values) {
    if (v !== undefined && v !== null && v !== '') return v;
  }
  return null;
}

async function merge(asra, joinmatrix, privacydev) {
  const uf = new UnionFind();

  const asraByName = new Map();
  for (const r of asra) {
    uf.add(r.name);
    if (r.client_domain) uf.union(r.name, r.client_domain);
    asraByName.set(r.name, r);
  }

  const jmByName = new Map();
  for (const r of joinmatrix) {
    uf.add(r.name);
    if (r.client_domain) uf.union(r.name, r.client_domain);
    if (r.server_domain) uf.union(r.name, r.server_domain);
    jmByName.set(r.name, r);
  }

  const pdByDomain = new Map();
  for (const r of privacydev) {
    uf.add(r.domain);
    pdByDomain.set(r.domain, r);
  }

  // Every domain that some source treats as a real server identity.
  const identityKeys = new Set([...asraByName.keys(), ...jmByName.keys()]);

  // privacydev hosts that did not already land in a group with a known server.
  const unresolved = [];
  for (const domain of pdByDomain.keys()) {
    const root = uf.find(domain);
    const sharesGroup = [...identityKeys].some((k) => uf.find(k) === root);
    if (!sharesGroup) unresolved.push(domain);
  }
  const linkResults = await linkAcrossSources(uf, unresolved);

  // Collect groups.
  const groups = new Map();
  const push = (key, kind, record) => {
    const root = uf.find(key);
    if (!groups.has(root)) groups.set(root, { asra: null, jm: null, pd: null, keys: new Set() });
    const g = groups.get(root);
    g.keys.add(key);
    if (kind === 'asra' && !g.asra) g.asra = record;
    if (kind === 'jm' && !g.jm) g.jm = record;
    if (kind === 'pd' && !g.pd) g.pd = record;
  };
  for (const [name, r] of asraByName) push(name, 'asra', r);
  for (const [name, r] of jmByName) push(name, 'jm', r);
  for (const [domain, r] of pdByDomain) push(domain, 'pd', r);

  const servers = [];
  for (const g of groups.values()) {
    const { asra: a, jm: j, pd: p } = g;
    if (!a && !j && !p) continue;

    // Canonical name: the mxid domain. asra and joinmatrix state it directly;
    // for a privacydev-only row it is whatever .well-known proved, and only
    // failing that does the raw host stand in.
    const discovered = p ? linkResults.get(p.domain)?.mxid_domain : undefined;
    const name = pickFirst(j?.name, a?.name, discovered, p?.domain);
    if (!name) continue;

    const sources = [];
    if (a) sources.push('asra');
    if (j) sources.push('joinmatrix');
    if (p) sources.push('privacydev');

    const aliases = [...g.keys].filter((k) => k !== name).sort();

    // Field precedence, by which source is actually authoritative:
    //  · software/version/last_check — asra (daily federation crawl) first
    //  · registration + descriptive  — joinmatrix (hand-curated)
    //  · privacy posture             — privacydev (its entire purpose)
    const server = {
      name,
      client_domain: pickFirst(j?.client_domain, a?.client_domain, p?.domain, name),
      software: pickFirst(a?.software, j?.software) ?? '',
      version: pickFirst(a?.version, j?.version) ?? '',
      last_check: a?.last_check || '',

      registration: {
        // joinmatrix states this outright (public_servers vs private_servers).
        // For the other two, presence in the list IS the statement: asra's
        // table is generated with `where reg=1`, and privacydev publishes
        // instances specifically so people can sign up to them.
        open: j ? j.registration_open : Boolean(a || p),
        vanilla: j?.using_vanilla_reg ?? null,
        method: j?.reg_method || '',
        link: j?.reg_link || '',
        captcha: pickFirst(
          j?.captcha,
          p?.recaptcha === true || p?.hcaptcha === true ? true : null,
          p?.recaptcha === false && p?.hcaptcha === false ? false : null,
        ),
        captcha_note: j?.captcha_note || '',
        recaptcha: p?.recaptcha ?? null,
        hcaptcha: p?.hcaptcha ?? null,
        email_required: pickFirst(j?.email, p?.email_required),
      },

      privacy: {
        tor_friendly: p?.tor_friendly ?? null,
        cloudflare: p?.cloudflare ?? null,
        stable: p?.stable ?? null,
        similarweb_rank: p?.similarweb_rank ?? null,
      },

      info: {
        description: j?.description || '',
        homepage: j?.homepage || '',
        rules: j?.rules || '',
        privacy_policy: j?.privacy_policy || '',
        isp: j?.isp || '',
        jurisdiction: j?.jurisdiction || '',
        languages: j?.languages ?? [],
        features: j?.features ?? [],
        longstanding: j?.longstanding ?? null,
      },

      ipv6: j?.ipv6 ?? null,
      sliding_sync: j?.sliding_sync ?? null,
      online_status: j?.online_status ?? null,
      ver_status: j?.ver_status ?? null,
      room_directory: j?.room_directory ?? null,

      sources,
      aliases,
    };

    const ev = [...g.keys].map((k) => linkResults.get(k)?.evidence).find(Boolean);
    if (ev) server.link_evidence = ev;

    // `name` and `sources` are guaranteed non-empty, so the pruned record can
    // never collapse to undefined.
    servers.push(prune(server));
  }

  servers.sort((x, y) => x.name.localeCompare(y.name));
  return servers;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

async function main() {
  const [asraSrc, jmSrc, pdSrc] = await Promise.all([
    loadSource('asra', parseAsra, { accept: 'text/html' }),
    loadSource('joinmatrix', parseJoinMatrix, { accept: 'application/json' }),
    loadSource('privacydev', parsePrivacyDev, { accept: 'text/csv,*/*' }),
  ]);

  const live = [asraSrc, jmSrc, pdSrc].filter((s) => s.ok).length;
  if (live === 0 && asraSrc.count + jmSrc.count + pdSrc.count === 0) {
    throw new Error('every source failed and no cache exists — refusing to write an empty list');
  }

  const servers = await merge(asraSrc.data, jmSrc.data, pdSrc.data);

  const openCount = servers.filter((s) => s.registration.open).length;
  const multi = servers.filter((s) => s.sources.length > 1).length;

  const payload = {
    version: SCHEMA_VERSION,
    generated_at: new Date().toISOString(),
    // A client should treat anything older than a couple of days as suspect.
    refresh_interval_hours: 24,
    counts: {
      total: servers.length,
      open_registration: openCount,
      merged_from_multiple_sources: multi,
    },
    sources: [asraSrc, jmSrc, pdSrc].map((s) => ({
      id: s.id,
      url: s.url,
      ok: s.ok,
      stale: s.stale,
      count: s.count,
      // Which egress actually served this. A source that only ever answers
      // `via: "proxy"` is a source whose upstream has blocked CI outright —
      // worth seeing in the published file rather than only in a run log.
      ...(s.via && s.via !== 'direct' ? { via: s.via } : {}),
      ...(s.error ? { error: s.error } : {}),
      ...(s.fetched_at ? { cached_at: s.fetched_at } : {}),
      // Age of the cached copy, so consumers can tell a one-off blip from a
      // source that has genuinely gone away. An upstream being briefly slow is
      // routine; warning users about it every time is just noise.
      ...(s.stale && s.fetched_at
        ? {
            cache_age_days: Math.floor(
              (Date.now() - new Date(s.fetched_at).getTime()) / 86_400_000,
            ),
          }
        : {}),
    })),
    servers,
  };

  await mkdir(API_DIR, { recursive: true });
  await writeFile(OUT_FILE, `${JSON.stringify(payload, null, 1)}\n`);

  log(
    `wrote ${path.relative(ROOT, OUT_FILE)} — ${servers.length} servers ` +
      `(${openCount} open registration, ${multi} merged from >1 source)`,
  );
  for (const s of payload.sources) {
    log(
      `  ${s.id.padEnd(11)} ok=${s.ok} count=${s.count}` +
        `${s.via ? ` via=${s.via}` : ''}${s.stale ? ' STALE' : ''}`,
    );
  }

  // Staleness is tolerable — that is what the cache is for — but only for a
  // while. privacydev sat stale for 21 consecutive green runs because nothing
  // ever escalated. Annotate, so a prolonged outage is visible on the run
  // itself; the workflow's health gate turns it red after the data is safely
  // published.
  for (const s of payload.sources) {
    if (!s.stale) continue;
    const age = s.cache_age_days;
    const how = Number.isFinite(age) ? `${age}d old` : 'no cache at all';
    const msg = `source ${s.id} is stale (${how}) — ${s.error ?? 'no error recorded'}`;
    if (Number.isFinite(age) && age >= STALE_ALARM_DAYS) annotate('error', msg);
    else annotate('warning', msg);
  }
}

main().catch((err) => {
  console.error('[servers] FATAL', err);
  process.exit(1);
});
